on: pull_request
name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.17.x"
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn lint
